Fred.ImportExport/Fred.ImportExport.Web/Controllers/RepriseDonneesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Fred.Entities.Organisation.Tree;
using Fred.ImportExport.Business.Cache.SynchronizationFredWeb.HangfireFilter;
using Fred.ImportExport.Business.Common;
using Fred.ImportExport.Business.RepriseDonnees;
using Fred.ImportExport.Resources.Resources;
using Fred.ImportExport.Web.Models;

namespace Fred.ImportExport.Web.Controllers
{
    public class RepriseDonneesController : Controller
    {
        private readonly IRepriseDonneesViewManager repriseDonneesViewManager;

        public RepriseDonneesController(IRepriseDonneesViewManager repriseDonneesViewManager)
        {
            this.repriseDonneesViewManager = repriseDonneesViewManager;
        }

        // GET: RepriseDonnees
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UpdateCis()
        {
            var model = new RepriseDonneesModel();

            model.Groupes = GetListItems();

            return View(nameof(UpdateCis), model);
        }

        private List<SelectListItem> GetListItems()
        {
            var groupes = repriseDonneesViewManager.GetAllGroupes();

            List<SelectListItem> items = new List<SelectListItem>();

            foreach (var groupe in groupes)
            {
                items.Add(new SelectListItem { Text = groupe.Code, Value = groupe.GroupeId.ToString() });
            }
            return items;
        }

        private List<SelectListItem> GetListItems(List<int> groupeIds)
        {
            var groupes = repriseDonneesViewManager.GetAllGroupes().Where(x => groupeIds.Contains(x.GroupeId));

            List<SelectListItem> items = new List<SelectListItem>();

            foreach (var groupe in groupes)
            {
                items.Add(new SelectListItem { Text = groupe.Code, Value = groupe.GroupeId.ToString() });
            }
            return items;
        }

        [HttpPost]
        public ActionResult UpdateCis(RepriseDonneesModel repriseDonneesModel)
        {
            Execute(repriseDonneesModel, (groupeId, file) => repriseDonneesViewManager.ImportCis(groupeId, file.InputStream).ErrorMessages);

            repriseDonneesModel.Groupes = GetListItems();

            return View(repriseDonneesModel);
        }

        public ActionResult CreateCommandesAndReceptions()
        {
            var model = new RepriseDonneesModel();

            model.Groupes = GetListItems();

            return View(nameof(CreateCommandesAndReceptions), model);
        }


        [HttpPost]
        public ActionResult CreateCommandesAndReceptions(RepriseDonneesModel repriseDonneesModel)
        {
            Execute(repriseDonneesModel, (groupeId, file) => repriseDonneesViewManager.CreateCommandeAndReceptions(groupeId, file.InputStream).ErrorMessages);

            repriseDonneesModel.Groupes = GetListItems();

            return View(repriseDonneesModel);
        }

        public ActionResult CreateRapports()
        {
            var model = new RepriseDonneesModel
            {
                Groupes = GetListItems()
            };
            return View(nameof(CreateRapports), model);
        }


        [HttpPost]
        public ActionResult CreateRapports(RepriseDonneesModel repriseDonneesModel)
        {
            Execute(repriseDonneesModel, (groupeId, file) => repriseDonneesViewManager.ImportRapports(groupeId, file.InputStream).ErrorMessages);
            repriseDonneesModel.Groupes = GetListItems();

            return View(repriseDonneesModel);
        }


        public ActionResult ValidationCommandes()
        {
            var model = new RepriseDonneesModel();

            return View(nameof(ValidationCommandes), model);
        }


        [HttpPost]
        public ActionResult ValidationCommandes(RepriseDonneesModel repriseDonneesModel)
        {
            //ici pas de selection de groupe donc groupeid = 0 => pas d'incidence sur le code de la validation car non utilisé dans le code de la validation
            // pas de refacto du code Execute car complexification inutile
            repriseDonneesModel.SelectedGroupe = "0";

            Execute(repriseDonneesModel, (groupeId, file) => repriseDonneesViewManager.ValidationCommandes(groupeId, file.InputStream).ErrorMessages);

            repriseDonneesModel.Groupes = GetListItems();

            return View(repriseDonneesModel);
        }

        private void Execute(RepriseDonneesModel repriseDonneesModel, Func<int, HttpPostedFileBase, List<string>> executeFunc)
        {
            if (GetUploadedFile(repriseDonneesModel, out HttpPostedFileBase file))
            {
                return;
            }

            if (GetSelectedGroup(repriseDonneesModel, out int groupeId))
            {
                return;
            }

            try
            {
                repriseDonneesModel.Errors = executeFunc(groupeId, file);

                FillViewBag(repriseDonneesModel);
            }
            catch (Exception ex)
            {
                ViewBag.Message = "ERROR:"
                    + Environment.NewLine
                    + " - "
                    + ex.Message
                    + Environment.NewLine
                    + " - "
                    + ex.InnerException?.Message
                    + Environment.NewLine
                    + " - "
                    + ex.InnerException?.InnerException?.Message;
            }
        }

        private async Task ExecuteAsync(RepriseDonneesModel repriseDonneesModel, Func<int, HttpPostedFileBase, Task<List<string>>> executeFunc)
        {
            if (GetUploadedFile(repriseDonneesModel, out HttpPostedFileBase file))
            {
                return;
            }

            if (GetSelectedGroup(repriseDonneesModel, out int groupeId))
            {
                return;
            }

            try
            {
                repriseDonneesModel.Errors = await executeFunc(groupeId, file);

                FillViewBag(repriseDonneesModel);

            }
            catch (Exception ex)
            {
                ViewBag.Message = "ERROR:"
                                  + Environment.NewLine
                                  + " - "
                                  + ex.Message
                                  + Environment.NewLine
                                  + " - "
                                  + ex.InnerException?.Message
                                  + Environment.NewLine
                                  + " - "
                                  + ex.InnerException?.InnerException?.Message;
            }
        }

        private bool GetUploadedFile(RepriseDonneesModel repriseDonneesModel, out HttpPostedFileBase file)
        {
            file = repriseDonneesModel.Files[0];
            if (file != null && file.ContentLength > 0)
            {
                return false;
            }

            ViewBag.Message = Resource.RepriseDonneesController_Veuillez_selectionner_un_Fichier;

            return true;

        }

        private bool GetSelectedGroup(RepriseDonneesModel repriseDonneesModel, out int groupeId)
        {
            if (int.TryParse(repriseDonneesModel.SelectedGroupe, out groupeId))
            {
                return false;
            }

            ViewBag.Message = Resource.RepriseDonneesController_Veuillez_selectionner_un_groupe;

            return true;

        }

        private void FillViewBag(RepriseDonneesModel repriseDonneesModel)
        {
            if (repriseDonneesModel.Errors != null && repriseDonneesModel.Errors.Any())
            {
                ViewBag.Message = Resource.RepriseDonneesController_Echec_Insertion_dans_Fred;
            }
            else
            {
                ViewBag.Message = Resource.RepriseDonneesController_Insertion_dans_Fred_reussie;
            }
        }

        public ActionResult CreatePlanTaches()
        {
            var model = new RepriseDonneesModel
            {
                Groupes = GetListItems()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult CreatePlanTaches(RepriseDonneesModel repriseDonneesModel)
        {
            Execute(repriseDonneesModel, (groupeId, file) => repriseDonneesViewManager.CreatePlanTaches(groupeId, file.InputStream).ErrorMessages);

            repriseDonneesModel.Groupes = GetListItems();

            return View(repriseDonneesModel);
        }

        public ActionResult CreatePersonnel()
        {
            RepriseDonneesModel model = new RepriseDonneesModel
            {
                Groupes = GetListItems()
            };

            return View(nameof(CreatePersonnel), model);
        }

        [HttpPost]
        public ActionResult CreatePersonnel(RepriseDonneesModel repriseDonneesModel)
        {
            Execute(repriseDonneesModel, (groupeId, file) => repriseDonneesViewManager.CreatePersonnel(groupeId, file.InputStream).ErrorMessages);

            repriseDonneesModel.Groupes = GetListItems();

            return View(repriseDonneesModel);
        }

        public ActionResult CreateMateriel()
        {
            RepriseDonneesModel model = new RepriseDonneesModel
            {
                Groupes = GetListItems()
            };

            return View(nameof(CreateMateriel), model);
        }

        [HttpPost]
        public ActionResult CreateMateriel(RepriseDonneesModel repriseDonneesModel)
        {
            Execute(repriseDonneesModel, (groupeId, file) => repriseDonneesViewManager.CreateMateriel(groupeId, file.InputStream).ErrorMessages);

            repriseDonneesModel.Groupes = GetListItems();

            return View(repriseDonneesModel);
        }

        public ActionResult CreateIndemniteDeplacement()
        {
            RepriseDonneesModel model = new RepriseDonneesModel

Fred.ImportExport/Fred.ImportExport.Web/Views/RepriseDonnees/CreateCommandesAndReceptions.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Reprise de données des commandes et des receptions";
}
@section styles {
    @Styles.Render("~/bundles/reprisedonnees.css")
}
@section scripts {
    @Scripts.Render("~/bundles/reprisedonnees.js")
}
@model Fred.ImportExport.Web.Models.RepriseDonneesModel
<h2>Création des commandes et receptions</h2>
@using (Html.BeginForm("CreateCommandesAndReceptions", "RepriseDonnees", FormMethod.Post, new { encType = "multipart/form-data" }))
{

    @Html.DropDownListFor(m => m.SelectedGroupe, Model.Groupes, "Selection du groupe")


    <br /><br />

    @Html.TextBoxFor(m => m.Files, new { type = "file", name = "Files" })<br /><br />

    <div>
        <label for="file">
            Lancer l'import
        </label>
    </div>


    <input type="submit"
           value="Importer"
           name="submitme"
           id="submitme" />
}
<br /><br />
@if (Model.Errors.Count > 0)
{

    <table id="myTable"
           class="table"
           cellspacing="0"
           style="border-collapse: collapse;width: 100%;table-layout: fixed;margin-top: 30px;font-family: Arial, Helvetica, sans-serif;">
        <thead>
            <tr>
                <th style="border: 1px solid black;height: 35px;background-color: rgb(221,235,247);">
                    Erreurs
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var erreur in Model.Errors)
            {
                <tr>
                    <td style="border: 1px solid black;text-align: left;height: 35px;">
                        @erreur
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<strong>@ViewBag.Message</strong>

Fred.ImportExport/Fred.ImportExport.Web/Views/RepriseDonnees/CreateIndemniteDeplacement.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Reprise de données des Indémnités de Déplacements";
}
@section styles {
    @Styles.Render("~/bundles/reprisedonnees.css")
}
@section scripts {
    @Scripts.Render("~/bundles/reprisedonnees.js")
}
@model Fred.ImportExport.Web.Models.RepriseDonneesModel
<h2>Reprise de données des Indémnités de Déplacements</h2>
@using (Html.BeginForm("CreateIndemniteDeplacement", "RepriseDonnees", FormMethod.Post, new { encType = "multipart/form-data" }))
{

    @Html.DropDownListFor(m => m.SelectedGroupe, Model.Groupes, "Selection du groupe")


    <br /><br />

    @Html.TextBoxFor(m => m.Files, new { type = "file", name = "Files" })<br /><br />

    <div>
        <label for="file">
            Lancer l'import
        </label>
    </div>


    <input type="submit"
           value="Importer"
           name="submitme"
           id="submitme" />
}
<br /><br />
@if (Model.Errors.Count > 0)
{

    <table id="myTable"
           class="table"
           cellspacing="0"
           style="border-collapse: collapse;width: 100%;table-layout: fixed;margin-top: 30px;font-family: Arial, Helvetica, sans-serif;">
        <thead>
            <tr>
                <th style="border: 1px solid black;height: 35px;background-color: rgb(221,235,247);">
                    Erreurs
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var erreur in Model.Errors)
            {
                <tr>
                    <td style="border: 1px solid black;text-align: left;height: 35px;">
                        @erreur
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<strong>@ViewBag.Message</strong>

Fred.ImportExport/Fred.ImportExport.Web/Views/RepriseDonnees/CreateMateriel.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Reprise de données des Materiels";
}
@section styles {
    @Styles.Render("~/bundles/reprisedonnees.css")
}
@section scripts {
    @Scripts.Render("~/bundles/reprisedonnees.js")
}
@model Fred.ImportExport.Web.Models.RepriseDonneesModel
<h2>Reprise de donnée des Materiels</h2>
@using (Html.BeginForm("CreateMateriel", "RepriseDonnees", FormMethod.Post, new { encType = "multipart/form-data" }))
{

    @Html.DropDownListFor(m => m.SelectedGroupe, Model.Groupes, "Selection du groupe")


    <br /><br />

    @Html.TextBoxFor(m => m.Files, new { type = "file", name = "Files" })<br /><br />

    <div>
        <label for="file">
            Lancer l'import
        </label>
    </div>


    <input type="submit"
           value="Importer"
           name="submitme"
           id="submitme" />
}
<br /><br />
@if (Model.Errors.Count > 0)
{

    <table id="myTable"
           class="table"
           cellspacing="0"
           style="border-collapse: collapse;width: 100%;table-layout: fixed;margin-top: 30px;font-family: Arial, Helvetica, sans-serif;">
        <thead>
            <tr>
                <th style="border: 1px solid black;height: 35px;background-color: rgb(221,235,247);">
                    Erreurs
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var erreur in Model.Errors)
            {
                <tr>
                    <td style="border: 1px solid black;text-align: left;height: 35px;">
                        @erreur
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<strong>@ViewBag.Message</strong>

Fred.ImportExport/Fred.ImportExport.Web/Views/RepriseDonnees/CreatePersonnel.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Reprise de données des Personnels";
}
@section styles {
    @Styles.Render("~/bundles/reprisedonnees.css")
}
@section scripts {
    @Scripts.Render("~/bundles/reprisedonnees.js")
}
@model Fred.ImportExport.Web.Models.RepriseDonneesModel
<h2>Reprise de donnée des Personnels</h2>
@using (Html.BeginForm("CreatePersonnel", "RepriseDonnees", FormMethod.Post, new { encType = "multipart/form-data" }))
{

    @Html.DropDownListFor(m => m.SelectedGroupe, Model.Groupes, "Selection du groupe")


    <br /><br />

    @Html.TextBoxFor(m => m.Files, new { type = "file", name = "Files" })<br /><br />

    <div>
        <label for="file">
            Lancer l'import
        </label>
    </div>


    <input type="submit"
           value="Importer"
           name="submitme"
           id="submitme" />
}
<br /><br />
@if (Model.Errors.Count > 0)
{

    <table id="myTable"
           class="table"
           cellspacing="0"
           style="border-collapse: collapse;width: 100%;table-layout: fixed;margin-top: 30px;font-family: Arial, Helvetica, sans-serif;">
        <thead>
            <tr>
                <th style="border: 1px solid black;height: 35px;background-color: rgb(221,235,247);">
                    Erreurs
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var erreur in Model.Errors)
            {
                <tr>
                    <td style="border: 1px solid black;text-align: left;height: 35px;">
                        @erreur
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<strong>@ViewBag.Message</strong>

Fred.ImportExport/Fred.ImportExport.Web/Views/RepriseDonnees/CreatePlanTaches.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Reprise de données des plans de tâches";
}
@section styles {
    @Styles.Render("~/bundles/reprisedonnees.css")
}
@section scripts {
    @Scripts.Render("~/bundles/reprisedonnees.js")
}
@model Fred.ImportExport.Web.Models.RepriseDonneesModel
<h2>Reprise de données des plans de tâches</h2>
@using (Html.BeginForm("CreatePlanTaches", "RepriseDonnees", FormMethod.Post, new { encType = "multipart/form-data" }))
{

    @Html.DropDownListFor(m => m.SelectedGroupe, Model.Groupes, "Sélection du groupe", new { @class = "fredIE-select" })


    <br /><br />

    @Html.TextBoxFor(m => m.Files, new { type = "file", name = "Files" })<br /><br />

    <div>
        <label for="file">
            Lancer l'import
        </label>
    </div>


    <input type="submit"
           value="Importer"
           name="submitme"
           id="submitme" />
}
<br /><br />
@if (Model.Errors.Count > 0)
{

    <table id="myTable"
           class="table"
           cellspacing="0"
           style="border-collapse: collapse;width: 100%;table-layout: fixed;margin-top: 30px;font-family: Arial, Helvetica, sans-serif;">
        <thead>
            <tr>
                <th style="border: 1px solid black;height: 35px;background-color: rgb(221,235,247);">
                    Erreurs
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var erreur in Model.Errors)
            {
                <tr>
                    <td style="border: 1px solid black;text-align: left;height: 35px;">
                        @erreur
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<strong>@ViewBag.Message</strong>

Fred.ImportExport/Fred.ImportExport.Web/Views/RepriseDonnees/CreateRapports.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "import des rapports journaliers simplifiés";
}
@section styles {
    @Styles.Render("~/bundles/reprisedonnees.css")
}
@section scripts {
    @Scripts.Render("~/bundles/reprisedonnees.js")
}
@model Fred.ImportExport.Web.Models.RepriseDonneesModel
<h2>Création des rapports et rapports lignes</h2>
@using (Html.BeginForm("CreateRapports", "RepriseDonnees", FormMethod.Post, new { encType = "multipart/form-data" }))
{

    @Html.DropDownListFor(m => m.SelectedGroupe, Model.Groupes, "Selection du groupe")


    <br /><br />

    @Html.TextBoxFor(m => m.Files, new { type = "file", name = "Files" })<br /><br />

    <div>
        <label for="file">
            Lancer l'import
        </label>
    </div>


    <input type="submit"
           value="Importer"
           name="submitme"
           id="submitme" />
}
<br /><br />
@if (Model.Errors.Count > 0)
{

    <table id="myTable"
           class="table"
           cellspacing="0"
           style="border-collapse: collapse;width: 100%;table-layout: fixed;margin-top: 30px;font-family: Arial, Helvetica, sans-serif;">
        <thead>
            <tr>
                <th style="border: 1px solid black;height: 35px;background-color: rgb(221,235,247);">
                    Erreurs
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var erreur in Model.Errors)
            {
                <tr>
                    <td style="border: 1px solid black;text-align: left;height: 35px;">
                        @erreur
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<strong>@ViewBag.Message</strong>

Fred.ImportExport/Fred.ImportExport.Web/Views/RepriseDonnees/ImportCiFromAnaelAndSendToSap.cshtml
@{
    ViewBag.Title = "Import des CIs depuis un fichier excel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles {
    @Styles.Render("~/bundles/reprisedonnees.css")
}
@section scripts {
    @Scripts.Render("~/bundles/reprisedonnees.js")
}
@model Fred.ImportExport.Web.Models.RepriseDonneesModel
<h2>Importation des Cis</h2>
@using (Html.BeginForm("ImportCiFromAnaelAndSendToSap", "RepriseDonnees", FormMethod.Post, new { encType = "multipart/form-data" }))
{

    @Html.DropDownListFor(m => m.SelectedGroupe, Model.Groupes, "Selection du groupe")


    <br /><br />

    @Html.TextBoxFor(m => m.Files, new { type = "file", name = "Files" })<br /><br />

    <div>
        <label for="file">
            Lancer l'import
        </label>
    </div>


    <input type="submit"
           value="Importer"
           name="submitme"
           id="submitme" />
}
<br /><br />
@if (Model.Errors.Count > 0)
{

    <table id="myTable"
           class="table"
           cellspacing="0"
           style="border-collapse: collapse;width: 100%;table-layout: fixed;margin-top: 30px;font-family: Arial, Helvetica, sans-serif;">
        <thead>
            <tr>
                <th style="border: 1px solid black;height: 35px;background-color: rgb(221,235,247);">
                    Erreurs
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var erreur in Model.Errors)
            {
                <tr>
                    <td style="border: 1px solid black;text-align: left;height: 35px;">
                        @erreur
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<strong>@ViewBag.Message</strong>

Fred.ImportExport/Fred.ImportExport.Web/Views/RepriseDonnees/ImportFournisseursFromAnaelAndSendToSap.cshtml
@{
    ViewBag.Title = "Import des Fournisseurs depuis un fichier excel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles {
    @Styles.Render("~/bundles/reprisedonnees.css")
}
@section scripts {
    @Scripts.Render("~/bundles/reprisedonnees.js")
}
@model Fred.ImportExport.Web.Models.RepriseDonneesModel
<h2>Importation des Fournisseurs</h2>
@using (Html.BeginForm("ImportFournisseursFromAnaelAndSendToSap", "RepriseDonnees", FormMethod.Post, new { encType = "multipart/form-data" }))
{

    @Html.DropDownListFor(m => m.SelectedGroupe, Model.Groupes, "Selection du groupe")


    <br /><br />

    @Html.TextBoxFor(m => m.Files, new { type = "file", name = "Files" })<br /><br />

    <div>
        <label for="file">
            Lancer l'import
        </label>
    </div>


    <input type="submit"
           value="Importer"
           name="submitme"
           id="submitme" />
}
<br /><br />
@if (Model.Errors.Count > 0)
{

    <table id="myTable"
           class="table"
           cellspacing="0"
           style="border-collapse: collapse;width: 100%;table-layout: fixed;margin-top: 30px;font-family: Arial, Helvetica, sans-serif;">
        <thead>
            <tr>
                <th style="border: 1px solid black;height: 35px;background-color: rgb(221,235,247);">
                    Erreurs
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var erreur in Model.Errors)
            {
                <tr>
                    <td style="border: 1px solid black;text-align: left;height: 35px;">
                        @erreur
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<strong>@ViewBag.Message</strong>

Fred.ImportExport/Fred.ImportExport.Web/Views/RepriseDonnees/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Reprise de données";
}
<h2>Sélectionner un type d'import</h2>
<strong>Mise à jour des centres d'imputation</strong>
<li>@Html.ActionLink("Reprise Données - Mise à jour des CIs", "UpdateCis", "RepriseDonnees")</li>
<br />
<br />
<strong>Création des commandes et réceptions</strong>
<li>@Html.ActionLink("Reprise Données - Création des commandes et réceptions", "CreateCommandesAndReceptions", "RepriseDonnees")</li>
<br />
<br />
<strong>Validation commandes outil 2</strong>
<li>@Html.ActionLink("Reprise Données - Validation commandes ", "ValidationCommandes", "RepriseDonnees")</li>
<br />
<br />
<strong>Création des rapports et rapports lignes</strong>
<li>@Html.ActionLink("Import rapports journaliers simplifiés Données", "CreateRapports", "RepriseDonnees")</li>
<br />
<br />
<strong>Import de plans de tâches</strong>
<li>@Html.ActionLink("Reprise Données des plans de tâches", "CreatePlanTaches", "RepriseDonnees")</li>
<br />
<br />
<strong>Import de Personnels</strong>
<li>@Html.ActionLink("Reprise Données des Personnels", "CreatePersonnel", "RepriseDonnees")</li>
<br />
<br />
<strong>Import de Matériels</strong>
<li>@Html.ActionLink("Reprise Données des Matériels", "CreateMateriel", "RepriseDonnees")</li>
<br />
<br />
<strong>Import d'Indemnités de Déplacement</strong>
<li>@Html.ActionLink("Reprise Données des Indémnités de Déplacement", "CreateIndemniteDeplacement", "RepriseDonnees")</li>
<br />
<br />
<strong>Importation des CIs</strong>
<li>@Html.ActionLink("Importation des CIs", "ImportCiFromAnaelAndSendToSap", "RepriseDonnees")</li>
<br />
<br />
<strong>Importation des Fournisseurs</strong>
<li>@Html.ActionLink("Importation des Fournisseurs", "ImportFournisseursFromAnaelAndSendToSap", "RepriseDonnees")</li>

Fred.ImportExport/Fred.ImportExport.Web/Views/RepriseDonnees/UpdateCis.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Reprise de données des cis";
}
@section styles {
    @Styles.Render("~/bundles/reprisedonnees.css")
}
@section scripts {
    @Scripts.Render("~/bundles/reprisedonnees.js")
}
@model Fred.ImportExport.Web.Models.RepriseDonneesModel
<h2>Mise à jour des centres d'imputations</h2>
@using (Html.BeginForm("UpdateCis", "RepriseDonnees", FormMethod.Post, new { encType = "multipart/form-data" }))
{

    @Html.DropDownListFor(m => m.SelectedGroupe, Model.Groupes, "Selection du groupe")


    <br /><br />

    @Html.TextBoxFor(m => m.Files, new { type = "file", name = "Files" })<br /><br />

    <div>
        <label for="file">
            Lancer l'import
        </label>
    </div>


    <input type="submit"
           value="Importer"
           name="submitme"
           id="submitme" />
}
<br /><br />
@if (Model.Errors.Count > 0)
{

    <table id="myTable"
           class="table"
           cellspacing="0"
           style="border-collapse: collapse;width: 100%;table-layout: fixed;margin-top: 30px;font-family: Arial, Helvetica, sans-serif;">
        <thead>
            <tr>
                <th style="border: 1px solid black;height: 35px;background-color: rgb(221,235,247);">
                    Erreurs
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var erreur in Model.Errors)
            {
                <tr>
                    <td style="border: 1px solid black;text-align: left;height: 35px;">
                        @erreur
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<strong>@ViewBag.Message</strong>